# Generated by Django 4.1.4 on 2022-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_title",
            field=models.CharField(
                default="This is a sub title", max_length=200, null=True
            ),
        ),
    ]
