# Generated by Django 4.0.5 on 2022-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.png", upload_to="images/"
            ),
        ),
    ]
